# Generated by Django 3.2.4 on 2021-06-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='author')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retail_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('availble', 'availble'), ('rent', 'rent'), ('sold', 'sold')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books_app.category')),
            ],
        ),
    ]
